### ISSUE TITLE
Themes don't support PROMPT_DIRTRIM

### ISSUE THREAD

**Issue by colemickens** [Eriner/zim#13]
It would be nice if the default themes supported PROMPT_DIRTRIM so that the prompt length can be limited. This is especially useful with the `eriner` theme.

**Comment by Eriner** [comment]
How about just shortening the PWD in general? 

See the `eriner` prompt in this branch:
https://github.com/Eriner/zim/tree/shortpwd

**Comment by Eriner** [comment]
To be clear, this is what I *will* be doing for the `eriner` prompt. The reason I ask is because the issue states: 
> It would be nice if the default theme**s** supported PROMPT_DIRTRIM.

Taking this into account, what I'm really asking is if you would prefer that `${PROMPT_DIRTRIM}` be applied to other (single-line) prompts, or if you would prefer the method I used. Just curious.

**Comment by colemickens** [comment]
I'd prefer to just have the same thing everywhere. What you have in that branch looks nice. Thanks!

**Comment by Eriner** [comment]
Closed by https://github.com/Eriner/zim/commit/be23020b2ef6efd7148c5610b0844c52a826aa4d
