### ISSUE TITLE
SSH module does not work on OpenBSD

### ISSUE THREAD

**Issue by aplatest** [Eriner/zim#55]
OpenBSD has bsd grep, which does not do colour.

#54 fixes grep, and thus fixes SSH

PS, you prefer both an issue and a pull request, or just pull requests?

**Comment by Eriner** [comment]
Fixing the color may fix the temporary issue, but it doesn't fix the real problem. I need to  go through and replace `grep` and `sed` with `command grep` and `command sed` so that aliases do not impact the result of those commands. (And also make things as compatible as possible accross operating systems.)

That said, yes, this is (seemingly) a band-aid for this problem.

**Comment by aplatest** [comment]
If you have a better way of doing it (you might end up with if openbsd/if freebsd/if netbsd etc) let me know, I'm reading through the source now and just fixing *my* needs :-)
