### ISSUE TITLE
Improve installation section in README.md

### ISSUE THREAD

**Issue by bijancn** [Eriner/zim#96]
First of all: Great work! Coming from prezto, I really felt a nice speed-up and hope to encounter less hanging prompts as well as more active development.

A minor hiccup was the installation. I copied this part

```
for template_file ( ${ZDOTDIR:-${HOME}}/.zim/templates/* ); do
  user_file="${ZDOTDIR:-${HOME}}/.${template_file:t}"
  touch ${user_file}
  ( print -rn "$(<${template_file})$(<${user_file})" >! ${user_file} ) 2>/dev/null
done
```

Only find myself with a broken `.zshrc`. I now know you have to fix something with the script as noted in #94 but I think it's better to just tell people to load it with

```
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
```

(writing in other peoples `.zshrc` feels really unappropriate).
Furthermore, you should say that customization of loaded modules is done in `~/.zimrc` (something I found out only after inspecting `.zim/templates`) and some magic happens in `~/zlogin` (does this have to be a separate file and can't be done within zim?).
Improving the all-with-one-command experience a la oh-my-zsh is a less important feature for the future IMHO as most users come from `oh-my-zsh`, `prezto`, `zplug`, etc. and like to have control over their configuration files.

PS: I am posting here as it seems you are not using https://github.com/zimframework/zim for development yet. I would suggest to make the transition swiftly even if the start might not be perfect but otherwise you end up with two trackers and everyone is confused #beenThere .

**Comment by Eriner** [comment]
> writing in other peoples `.zshrc` feels really unappropriate

I don't have any issue with this. The reason I just have a "blob" to paste during installation is so that the process is as transparent (and compact) as possible. Eventually this will change, and we'll have a PGP signed installation script/tool, but the method in the Readme.md should always work, bar a bug or two that I still need to fix as mentioned in other issue reports.

> Furthermore, you should say that customization of loaded modules is done in ~/.zimrc (something I found out only after inspecting .zim/templates)

It seems that you failed to finish reading the installation instructions. From the Readme.md: "You're done! Enjoy your Zsh IMproved! Take some time to read about the available modules and tweak your .zshrc file."
